# Generated by Django 4.1.5 on 2023-01-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account_books", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Url",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin_url", models.URLField(max_length=255)),
                ("new_url", models.URLField(default="")),
            ],
            options={
                "db_table": "Url",
            },
        ),
    ]
