# Generated by Django 4.1.5 on 2023-01-13 00:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("account_books", "0003_url_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accountbooks",
            options={"ordering": ["date"]},
        ),
        migrations.AddField(
            model_name="accountbooks",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
