# Generated by Django 4.1.5 on 2023-01-13 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account_books", "0004_alter_accountbooks_options_accountbooks_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountbooks",
            name="balance",
            field=models.IntegerField(default=0),
        ),
    ]
